command_line_args:
    actor_lr: 0.0001
    alpha3: 0.8
    alpha_lr: 0.0003
    area_size: 6
    batch_size: 512
    collision_penalty: -300
    correction_cost_dist: 0.05
    cost: 10
    cost_coeff: 2
    cost_dist: 0.5
    cost_obs_dist: 1.8
    critic_lr: 0.0003
    danger_penalty_coeff: 3
    debug: false
    delta_action_scale: 3
    dt: 0.02
    edge_coeff: 2.5
    env: DubinsCar
    eval_epi: 100
    eval_interval: 40
    gamma: 0.99
    guide_reward_high: 4.0
    guide_reward_low: -1
    hidden_dims: !!python/tuple
    - 256
    - 256
    lambda_guide: 1.5
    log_dir: ./logs
    lyapunov_loss_coeff: 0.2
    max_step: 200
    n_rays: 32
    num_agents: 1
    obs: 8
    potential_obs_reward_coeff: 5
    project_name: GLAC_Car
    reach_reward: 5.0
    reward_scale: 5
    rho_min_coeff: 1.2
    rl_algo: GLAC
    save_interval: 50
    seed: 27
    start_timesteps: 3000
    steps: 1000
    success_reward: 100
    tau: 0.005
    tgt_reward_coeff: 50
    total_timesteps: 400000
    train_per_cycle: 80
    w_delta1: 1
    w_delta2: 0.1
    warning_dist2obs: 2.0
